#!/usr/bin/python3
import requests, json, os, sys

HOSTNAME = "localhost"
PORT = "8080"

url = "http://" + HOSTNAME + ":" + PORT + "/cfginfo"

response = requests.get(url)
if(response.status_code == 200):
    return_data = response.json()
    config_list = return_data["files"]
    for each_file in config_list:
        print(each_file)
else:
    # Will ideally never come to this condtition since no input is given
    print("Failure: cfginfo failed")
# print("tiny-1-1.cfg")
# print("tiny-2-2.cfg")
# print("tiny-3-3.cfg")
