#!/usr/bin/python3
import requests, json, os, sys

HOSTNAME = "localhost"
PORT = "8080"

url = "http://" + HOSTNAME + ":" + PORT + "/destroyall"
response = requests.delete(url)
if(response.status_code == 200 or response.status_code == 409):
    print("Success") 
else:
    print("Failure:")
